server:
  port: 8081
logging:
  level:
    org:
      springframework:
        web: debug
        jdbc: debug
      mybatis: debug
weibo:
  clientId: 1851593910
  clientSecret:
  redirectUri: https://passport.yhd.com/sina/callback.do

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/user
      username: root
      password: 123456
  thymeleaf:
    check-template: true
    cache: false